version: '3.8'

services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./data:/app/data  
        environment:
            - DATABASE_URL=sqlite:///./data/database.db
          
        restart: unless-stopped

        networks:
            - app-network
    networks:
        app-network:
            driver: bridge
